# Generated by Django 5.1.7 on 2025-03-31 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('development', 'Development'), ('system_design', 'System Design'), ('job_search', 'Job Search')], max_length=20, unique=True)),
                ('daily_target', models.PositiveIntegerField(default=3)),
                ('weekly_streak', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('development', 'Development'), ('system_design', 'System Design'), ('job_search', 'Job Search')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='app_task_categor_b5e931_idx'), models.Index(fields=['completed'], name='app_task_complet_e03d5c_idx')],
            },
        ),
    ]
