# Generated by Django 5.1.7 on 2025-04-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goal_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['category']},
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'category')},
        ),
    ]
