# Generated by Django 5.1.7 on 2025-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_goal_options_alter_goal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('development', 'Development'), ('system_design', 'System Design'), ('job_search', 'Job Search')], max_length=20),
        ),
    ]
