# Generated by Django 5.1.7 on 2025-04-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_goal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='goal',
            name='current_week_days_completed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='streak_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
