# Generated by Django 5.1.7 on 2025-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_goal_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
