# Generated by Django 5.1.7 on 2025-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goal_current_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='daily_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_daily_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
