# Generated by Django 5.1.7 on 2025-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
