# Generated by Django 5.1.7 on 2025-06-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
